### ISSUE TITLE
Can i deploy for Live streaming 

### ISSUE THREAD

**Issue by adarsh-dikhit** [zldrobit/tfjs-yolov5-example#10]
Hi, All
it is possible for live streaming or not ?

**Comment by zldrobit** [comment]
@adarsh-dikhit This repo does not support live streaming at the moment, but it is possible to enable streaming function with detection by adding WebRTC code.

**Comment by adarsh-dikhit** [comment]
Thank you

**Comment by adarsh-dikhit** [comment]
Thank you, for help
