### ISSUE TITLE
Bounding boxes are not placed correctly

### ISSUE THREAD

**Issue by govza** [zldrobit/tfjs-yolov5-example#13]
Bounding boxes doesn't seam to be correct and differ from the original detect.py boxes. 
Can't understand is it tfjs conversion or app drawing problem.

Here and in other images, boxes are usually drawn over top-half of the object.

![image](https://user-images.githubusercontent.com/1425574/163673521-c4a00b6c-1def-431e-86bb-b1eda4671bb9.png)

**Comment by zldrobit** [comment]
I could not reproduce the error, and I am using Firefox as a browser.
![image](https://user-images.githubusercontent.com/3896992/163780958-02141f29-e90d-42a0-9bfb-5de3888cef74.png)

PS: What browser (and its version) are you using?

**Comment by govza** [comment]
Thank you for your response. 
It looks like the tf inference on webgl of my gpu  GTX 850M doesn't work properly. Though it's all good with tf.setBackend("cpu") and on other computers.
