### ISSUE TITLE
How to bundle model files and avoid public access from browser 

### ISSUE THREAD

**Issue by Mas-Y** [zldrobit/tfjs-yolov5-example#14]
Hi @zldrobit. Is there a way to bundle the model files, so that we don’t have to put the model files in public folder for general access. When the user is using the in-browser app the user shouldn’t be able to download the model files (shouldn’t have access to the model files). 

Any help is appreciated. Thanks.

**Comment by zldrobit** [comment]
tfjs is a javascript module, and it works in the frontend (browser). The mechanism of javascript requires the browser to download a model file before inference. Maybe you could encrypt the model before downloading and decrypt the model on the browser with a one-time key. The user could only intercept the browser to get the original model. Another way is using a backend inference framework other than tfjs (e.g. tfjs node, TensorFlow, or Pytorch), so the inference is done on the server side. The user thus cannot touch the model.

**Comment by MasarratY** [comment]
@zldrobit Thank you so much for the quick response. I am only interested in client side implementation from the perspective of offline processing, So server side option is not in the scope.
Regarding, encryption and decryption if i interpreted your explanation correctly- you are saying the model will still be downloaded in the browser and user can have access to it.

**Comment by Mas-Y** [comment]
@zldrobit Thank you so much for the quick response. I am only interested in client side implementation from the perspective of offline processing, So server side option is not in the scope.
Regarding, encryption and decryption if i interpreted your explanation correctly- you are saying the model will still be downloaded in the browser and user can have access to it.

**Comment by Mas-Y** [comment]
@zldrobit is there a way to add additional parameter like some key/uuid parameter while converting to the model files itself, so that after downloading the model, the model can only be loaded and used if the key is provided. This way the original model will always require key to load.

Any thoughts of this

**Comment by zldrobit** [comment]
>@zldrobit is there a way to add additional parameter like some key/uuid parameter while converting to the model files itself, so that after downloading the model, the model can only be loaded and used if the key is provided. This way the original model will always require key to load.

@Mas-Y It could be done by downloading an encrypted model (replace the original path with an encrypted one in https://github.com/zldrobit/tfjs-yolov5-example/blob/f4a85e2200e6589541110e4f5ca8ef475e10248e/src/index.js#L8), and decrypting it with a provided key before loading it in https://github.com/zldrobit/tfjs-yolov5-example/blob/f4a85e2200e6589541110e4f5ca8ef475e10248e/src/index.js#L27-L33.

**Comment by Mas-Y** [comment]
@zldrobit Thank you for the detailed explanation and the support. Would try Implementing the same.
