### ISSUE TITLE
Failed to parse model JSON

### ISSUE THREAD

**Issue by krushal-kyada** [zldrobit/tfjs-yolov5-example#7]
Hi!
I'm getting Error as Unhandled Rejection (Error): Failed to parse model JSON on this repo example.
Can please help me fix it.?

I don't have experience working with JS if some can provide steps to fix it will be helpful.

```
Version details : 
tensorflow==2.6.0
tensorflowjs==3.11.0

npm -v
8.1.3
```

![Screenshot from 2021-11-18 12-23-37](https://user-images.githubusercontent.com/87109364/142366850-308b6d1d-9406-4131-9c65-bb68e0944d9d.png)

Thnks

**Comment by zldrobit** [comment]
@krushal-kyada Hi! Could you confirm the web of this repo works correctly in a browser? Could you provide a minimal reproducible example? From the messages above, you are calling the web application by an HTTP JSON method, but I am afraid that the web application of this repo does not provide an HTTP JSON interface.

**Comment by krushal-kyada** [comment]
Hi, I have just cloned the repo and trying to run that.
npm start opens up Mozilla firefox 
http://localhost:3000/tfjs-yolov5-example 

![Screenshot from 2021-11-23 15-38-28](https://user-images.githubusercontent.com/87109364/143005910-1da35e22-9757-4994-8b22-96de845b6f40.png)

Let me know if I am missing out on anything.

Thanks.

**Comment by zldrobit** [comment]
It seems that you haven't exported the tfjs yolov5 model yet. Plz follow the instruction in the repo README.md.
I excerpted it for convenience:
![image](https://user-images.githubusercontent.com/3896992/143161897-42853dc2-9508-404a-9934-9a3b9569ae99.png)

First, clone YOLO v5 repo and export a tfjs yolov5 model.
Second, clone this repo and link the model path.
Third,  run `npm install && npm start`.

**Comment by krushal-kyada** [comment]
Hi 

I have followed the above steps,

Also, have the converted model linked 

Converted model using 
```

git clone https://github.com/ultralytics/yolov5.git
python export.py --weights yolov5s.pt --include tfjs
```

![Screenshot from 2021-11-24 12-16-40](https://user-images.githubusercontent.com/87109364/143188577-024c4642-18a2-4056-bf60-190e24d8adf3.png)

Linked model using 
`ln -s ../../yolov5/yolov5s_web_model public/web_model`

![Screenshot from 2021-11-24 12-13-59](https://user-images.githubusercontent.com/87109364/143188469-532afba3-3c09-4e6e-8e9d-04a75d1c0ad7.png)

Just for reference :
`
npm install
`
![image](https://user-images.githubusercontent.com/87109364/143190127-b3918c7d-fd8e-4e43-b10e-f078dab70079.png)


Then too it's not working.
Let me know if I am missing anything.

Thanks 

Krushal

**Comment by zldrobit** [comment]
From the messages you provided, there seems to be no errors. Could you provide the output message from terminal after the command `npm start`? This message should contain some debug information needed to resolve the problem.

**Comment by krushal-kyada** [comment]
Please refer to the below snippet.
Mozilla Firefox  and terminal window 
![Screenshot from 2021-11-25 09-01-40](https://user-images.githubusercontent.com/87109364/143375502-07672806-9e01-48ed-a71b-caef36829a04.png)

**Comment by zldrobit** [comment]
My terminal output is different from yours considering the URL.
![image](https://user-images.githubusercontent.com/3896992/143439847-49487ebd-025b-4be9-95d8-6c1778839d5d.png)
It has no `tfjs-yolov5-example` suffix. Did you change any code in the repo?

**Comment by krushal-kyada** [comment]
Hi

I have not made any changes to the code file.
Followed the steps, cloned the repos, and npm start.

Below is my project structure,
Please verify the directory locations of both repo,

```
└── zldrobit
    ├── tfjs-yolov5-example
    │   ├── node_modules
    │   ├── package.json
    │   ├── package-lock.json
    │   ├── public
    │   │   ├── index.html
    │   │   └── web_model -> /home/krushalkyada/Project/TF_JS/Yolo/zldrobit/yolov5/yolov5s_web_model
    │   ├── README.md
    │   └── src
    │       ├── index.js
    │       └── styles.css
    └── yolov5
        ├── CONTRIBUTING.md
        ├── data
        ├── detect.py
        ├── Dockerfile
        ├── export.py
        ├── hubconf.py
        ├── LICENSE
        ├── models
        ├── README.md
        ├── requirements.txt
        ├── setup.cfg
        ├── train.py
        ├── tutorial.ipynb
        ├── utils
        ├── val.py
        ├── venv
        │   ├── bin
        │   ├── lib
        │   ├── pyvenv.cfg
        │   └── share
        ├── yolov5s.pb
        ├── yolov5s.pt
        ├── yolov5s_saved_model
        │   ├── assets
        │   ├── keras_metadata.pb
        │   ├── saved_model.pb
        │   └── variables
        └── yolov5s_web_model
            ├── group1-shard1of7.bin
            ├── group1-shard2of7.bin
            ├── group1-shard3of7.bin
            ├── group1-shard4of7.bin
            ├── group1-shard5of7.bin
            ├── group1-shard6of7.bin
            ├── group1-shard7of7.bin
            └── model.json
```
Thanks
Krushal

**Comment by zldrobit** [comment]
Hi. 
I found that your `web_model` directory is linked to `/home/Project/TF_JS/Yolo/zldrobit/yolov5/yolov5s_web_model`. I think it should be linked to `/home/krushalkyada/Project/TF_JS/Yolo/zldrobit/yolov5/yolov5s_web_model`, if your home directory is `/home/krushalkyada`. Maybe you have to relink the directory, and plz check the `web_model` directory with `ls` command.

**Comment by krushal-kyada** [comment]
It is connected to the web model from the Yolo folder. 
update : 

 web_model -> /home/krushalkyada/Project/TF_JS/Yolo/zldrobit/yolov5/yolov5s_web_model

![Screenshot from 2021-11-29 14-29-59](https://user-images.githubusercontent.com/87109364/143837867-6e332e7e-87c7-48f5-bb16-1c2d02973011.png)

Content of the linked folder
![Screenshot from 2021-11-29 14-29-45](https://user-images.githubusercontent.com/87109364/143837927-a01c1d53-ecfb-4b1b-8e26-35d3d7e22a2c.png)

**Comment by zldrobit** [comment]
Please share more messages to find the cause of the problem:
- Press `F12` in the browser to show the debug window and share the full debug stack. 
- Run `curl http://localhost:3000/web_model/model.json` and `curl http://localhost:3000/tfjs-yolov5-example/web_model/model.json` on terminal, and share the output messages in terminal.

**Comment by krushal-kyada** [comment]
Hi 
Please refer to the below screenshots:
F12 in the browser to show the debug window and share the full debug stack.

![Screenshot from 2021-11-29 16-01-14](https://user-images.githubusercontent.com/87109364/143853199-3b9aef72-0cc2-4a8a-9582-2f9bbb98dc93.png)

Output for the following command : 
```
curl http://localhost:3000/web_model/model.json 
```
![Screenshot from 2021-11-29 16-09-18](https://user-images.githubusercontent.com/87109364/143853925-33f8b713-5502-4f0d-ab54-2f29e564d024.png)
```
curl http://localhost:3000/tfjs-yolov5-example/web_model/model.json
```
this command gives the content of the model.json file. 
The below screenshot is part of the whole thing...

![Screenshot from 2021-11-29 16-16-21](https://user-images.githubusercontent.com/87109364/143854490-a944a0a1-0af2-42e1-9106-ab44515a17cc.png)

Looking at the response of curl http://localhost:3000/tfjs-yolov5-example/web_model/model.json

I have updated the index.js.
as 
```
const weights = 'http://localhost:3000/tfjs-yolov5-example/web_model/model.json';
```
instead of 
```
const weights = '/web_model/model.json';
```

And i was able to run the project, 

Is this a correct way to load the weights?

Thanks 

Krushal Kyada

**Comment by zldrobit** [comment]
Yes, that's the right way to load weights. As I remember, it's also the original code in this repo. You're welcome :D

**Comment by krushal-kyada** [comment]
Thanks a lot.
