### ISSUE TITLE
stuck with Loading model...

### ISSUE THREAD

**Issue by chucksylar** [zldrobit/tfjs-yolov5-example#8]
After running npm start, at http://localhost:3000 stuck at Loading model...how to fix this

**Comment by zldrobit** [comment]
The browser is downloading the model, and please wait. Considering the model size from around 10M to 100M+, it takes time. I shall improve the UI to indicate users for downloading models.

**Comment by zldrobit** [comment]
I am closing the issue. If you have any further questions, plz reopen it.
